### ISSUE TITLE
Document incident command process for non-SRC members

### ISSUE THREAD

**Issue by tallclair** [kubernetes/committee-security-response#140]
I'd like to create & document an incident response process that we can delegate better. This should include specific steps to follow, action items, timelines, etc. Ideally it could be handed off to non-SRC members who have never been involved in a Kubernetes security response before, and they'd be able to follow the instructions to lead a security response.

Considerations for non-SRC incident responders:

- They don't have access to HackerOne, distributors list, etc.  An SRC member will still need to act in a comms role, minimally for H1 involvement and to post announcements.
- They don't (shouldn't) have access to our issues tracker. We need a workflow where individual issues can be shared on a need-to-know basis. Ideas: google doc (meh, requires google account), GitHub security advisories on a dedicated org (SRC needs to be repo admins)
- Every non-SRC IC should have a dedicated SRC contact. Regular status updates should be shared with the SRC member.

**Comment by tallclair** [comment]
This would also be useful to SRC members, and should include checklists & timelines for response.

**Comment by PushkarJ** [comment]
Also, there is an opportunity to reuse some ideas / template from here: https://github.com/cncf/tag-security/blob/main/project-resources/templates/incident-response.md
