### ISSUE TITLE
Onboard @ritazh as associate

### ISSUE THREAD

**Issue by enj** [kubernetes/committee-security-response#156]
- [ ] kubernetes/security PR:
  - [x] README.md #158
- [ ] kubernetes/k8s.io PR: https://github.com/kubernetes/k8s.io/pull/3700
  - [x] groups/security-response-committee/groups.yaml
    - `distributors-announce@kubernetes.io`
- [ ] ~~kubernetes/community PR:~~
  - [ ] ~~sigs.yaml~~
  - [ ] ~~communication/slack-config/usergroups.yaml~~
  - [ ] ~~`make generate`~~
- [ ] ~~kubernetes/org PR:~~
  - [ ] ~~config/kubernetes/org.yaml~~
- [x] Verify Discuss account
- [x] github.com/kubernetes-security membership
- [ ] Slack
  - [x] Verify 2-factor auth
  - [ ] `#SRC-private` membership -> not sure about this?
  - [ ] `#security-release-team` membership -> not sure about this?
- [ ] Calendar meetings
- [ ] Google Docs access
cc @ritazh

**Comment by ritazh** [comment]
Confirming I have 2FA setup for K8s slack. Thanks @enj!
