### ISSUE TITLE
Onboard @cji

### ISSUE THREAD

**Issue by joelsmith** [kubernetes/committee-security-response#177]
- [x] kubernetes/security PR: https://github.com/kubernetes/committee-security-response/pull/176
  - [x] README.md
  - [x] OWNERS_ALIASES
  - [x] SECURITY_CONTACTS
- [x] kubernetes/k8s.io PR: https://github.com/kubernetes/k8s.io/pull/5212
  - [x] groups/security-response-committee/groups.yaml
    - `security@kubernetes.io`
    - `security-discuss-private@kubernetes.io`
    - `distributors-announce@kubernetes.io`
  - [x] OWNERS_ALIASES
- [x] kubernetes/community PR: https://github.com/kubernetes/community/pull/7282
  - [x] sigs.yaml
  - [x] communication/slack-config/usergroups.yaml
    - [x] Verify slack 2-factor auth
  - [x] `make generate`
- [x] kubernetes/org PR: https://github.com/kubernetes/org/pull/4195
  - [x] config/kubernetes/org.yaml
- [x] HackerOne project membership
  - [x] Verify 2-factor auth
- [x] OpsGenie rotation
  - [x] Add new user
  - [x] Update rotation
- [x] Mailing lists
  - [x] [Security Discuss](https://groups.google.com/forum/#!forum/kubernetes-security-discuss) - owner
  - [x] [Security Announce](https://groups.google.com/forum/#!forum/kubernetes-security-announce) - owner
  - [x] [Kubernetes Announce](https://groups.google.com/forum/#!forum/kubernetes-announce) - manager
  - [x] [Kubernetes Dev](https://groups.google.com/forum/#!forum/kubernetes-dev) - member
- [x] Verify Discuss account
- [x] github.com/kubernetes-security membership
- [x] Slack
  - [x] Verify 2-factor auth
  - [x] `#SRC-private` membership
  - [x] `#security-release-team` membership
- [ ] Calendar meetings
- [x] Google Docs access

**Comment by joelsmith** [comment]
https://github.com/kubernetes/community/pull/7282
https://github.com/kubernetes/k8s.io/pull/5212
https://github.com/kubernetes/committee-security-response/pull/176

**Comment by cji** [comment]
@joelsmith 
- 2fa enabled for H1 and Slack
- Discuss account https://discuss.kubernetes.io/u/cji/summary
- Dev mailing list joined
think that's everything but keeping an eye out for the h1 meeting

thank you!

**Comment by cji** [comment]
@joelsmith I noticed this is open with an unchecked item to add me to meetings. I see the SRC monthly on my calendar. Is this good to close now?

**Comment by joelsmith** [comment]
@cji do you have a meeting with H1 on your calendar on Thursday, July 13th? If you have that, then I think we can close it.

**Comment by cji** [comment]
I confirmed I have the meeting on my calendar - thanks!
