### ISSUE TITLE
Question on SECURITY_CONTACTS in subproject (kubespray)

### ISSUE THREAD

**Issue by VannTen** [kubernetes/committee-security-response#205]
Hi,

I've been the main kubespray maintainer for some time, and while doing some cleanup, I come across the [SECURITY_CONTACTS](https://github.com/kubernetes-sigs/kubespray/blob/master/SECURITY_CONTACTS) in Kubespray repo.

First, it seems pretty outdated, as every names in it (except @floryut ) are no longer active in Kubespray.

Second, I'm not completely sure of the relevance of the Embargo policy.

Specifically :
```
The patch files and any derived patched binaries are included in the embargo, and must not be distributed or made available to external parties before the public disclosure is made.

However, a fully-hosted patched kube-apiserver can be deployed prior to the embargo lift date if users do not have direct access to the binary and if the patch only applies to the kube-apiserver.

Other fully-hosted patched components can also be deployed prior to the embargo lift date only if all users with access to the components and/or clusters are internal to the Kubernetes distributor.
```

I assume this is meant for hosted Kubernetes solutions from cloud provider. Since Kubespray is basically a tool to deploy your own cluster, I'm not sure what exactly we could accomplish with embargoed information of that sort. And if we can't do anything with it, why having it ?

So is there another purpose to that file beside private distributors stuff ? Do we need to keep it up to date ? Should we just delete it ?

Thanks.

**Comment by cji** [comment]
Hi @VannTen - the Security Response Committee uses the SECURITY_CONTACTS to reach out to owners when we receive vulnerability submissions, usually through the Hackerone bug bounty program. So definitely please keep it up to date if it isn't!

As for the embargo policy, I think the intent for something like kubespray is that we, the SRC, will be sharing non-public vulnerability information with you as security contacts, and expect you to agree not to disclose that information, for the safety of our users, without coordination. This may need some rewording as you're right, this is mostly focused on distributors getting early patches, and the section you highlighted doesn't really make sense for you as a maintainer or someone working on a fix.

**Comment by VannTen** [comment]
Thanks for the clarification 👍, I will update it then
